### ISSUE TITLE
Packagist support

### ISSUE THREAD

**Issue by coffeetalkh** [anetwork/sidenav#2]
Please link this repository to Packagist and also add webhooks for auto-update the relseases.

**Comment by iamalirezaj** [comment]
The SideNav package now on packagist and also add webhook for auto-update the releases
you can install with composer now
the package now on development step
you must install package with dev-master version
```composer require anetwork/sidenav:dev-master```

**Comment by coffeetalkh** [comment]
@iamalirezaj Thanks alireza
