### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by imehdihosseini** [anetwork/sidenav#5]
- Change Helper file design pattern to classify support except functional structure
- CamelCase code style for [defining](https://github.com/anetwork/sidenav/blob/master/src/Menu.php#L43) attributes
- Method's comments should contain author and since params.
- Please restyle your code with code sniffer PSR-2 code style

**Comment by iamalirezaj** [comment]
removed the helper functions from source
and added a trait SideNavHelpers to project for
use in SideNav object

**Comment by iamalirezaj** [comment]
CamelCase code style has been complated
and Method's comments has author and since now
also the codes has PSR-2 code style
